/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_v1_intake_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/batches/{batch_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Source */
        post: operations["upload_source_api_v1_intake_batches__batch_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/sources/{source_file_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_intake_sources__source_file_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/sources/{source_file_id}/mapping-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Mapping Proposal */
        post: operations["create_mapping_proposal_api_v1_intake_sources__source_file_id__mapping_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/mappings/{mapping_version_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Mapping */
        post: operations["confirm_mapping_api_v1_intake_mappings__mapping_version_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/sources/{source_file_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Source */
        post: operations["validate_source_api_v1_intake_sources__source_file_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/issues/{quality_issue_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge Warning */
        post: operations["acknowledge_warning_api_v1_intake_issues__quality_issue_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/imports/{import_version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Import */
        post: operations["publish_import_api_v1_intake_imports__import_version_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/batches/{batch_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version History */
        get: operations["version_history_api_v1_intake_batches__batch_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Overview */
        get: operations["dashboard_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investigation Context */
        get: operations["investigation_context_api_v1_investigations__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{finding_id}/evidence/{evidence_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Evidence */
        post: operations["decide_evidence_api_v1_investigations__finding_id__evidence__evidence_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{finding_id}/conclusion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Conclusion */
        put: operations["save_conclusion_api_v1_investigations__finding_id__conclusion_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{finding_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Finding */
        post: operations["transition_finding_api_v1_investigations__finding_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copilot/investigations/{finding_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Investigation Question */
        post: operations["ask_investigation_question_api_v1_copilot_investigations__finding_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copilot/explain-mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Mapping */
        post: operations["explain_mapping_api_v1_copilot_explain_mapping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copilot/report-outline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft Report Outline */
        post: operations["draft_report_outline_api_v1_copilot_report_outline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveFilters */
        ActiveFilters: {
            /**
             * Period View
             * @enum {string}
             */
            period_view: "month" | "ytd";
            /** Organization Id */
            organization_id?: string | null;
            /** Customer Segment Id */
            customer_segment_id?: string | null;
            /** Logistics Product Id */
            logistics_product_id?: string | null;
            /** Region Id */
            region_id?: string | null;
            /** Is Total Scope */
            is_total_scope: boolean;
        };
        /** AnalysisResultContext */
        AnalysisResultContext: {
            /** Analysis Result Id */
            analysis_result_id: string;
            /** Playbook Code */
            playbook_code: string;
            /** Playbook Version */
            playbook_version: number;
            /** Status */
            status: string;
            /** Comparison Basis */
            comparison_basis: string;
            /** Impact Amount */
            impact_amount: string;
            /** Unit */
            unit: string;
            /** Reconciliation Difference */
            reconciliation_difference: string;
            /** Reconciliation Tolerance */
            reconciliation_tolerance: string;
            /** Source Record Count */
            source_record_count: number;
            /** Degradation Code */
            degradation_code: string | null;
            /** Degradation Message */
            degradation_message: string | null;
        };
        /** BatchCreateRequest */
        BatchCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** BatchResponse */
        BatchResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "validating" | "blocked" | "ready" | "published";
            /** Description */
            description: string | null;
        };
        /** Body_upload_source_api_v1_intake_batches__batch_id__sources_post */
        Body_upload_source_api_v1_intake_batches__batch_id__sources_post: {
            /**
             * Workbook
             * @description Macro-free XLSX workbook
             */
            workbook: string;
        };
        /** BridgeDriver */
        BridgeDriver: {
            /** Driver Code */
            driver_code: string;
            /** Label */
            label: string;
            contribution: components["schemas"]["DashboardValue"];
        };
        /** ColumnProfileResponse */
        ColumnProfileResponse: {
            /** Column */
            column: string;
            /** Header */
            header: string;
            /** Stable Field Id */
            stable_field_id: string | null;
            /** Inferred Type */
            inferred_type: string;
            /** Nullable */
            nullable: boolean;
            /** Non Null Count */
            non_null_count: number;
        };
        /**
         * ConclusionResponse
         * @description Acknowledgement of a stored Finance BP conclusion.
         */
        ConclusionResponse: {
            /** Finding Id */
            finding_id: string;
            /** Status */
            status: string;
            /** Review Sequence */
            review_sequence: number;
            /** Decision */
            decision: string;
        };
        /** ConclusionState */
        ConclusionState: {
            /** Exists */
            exists: boolean;
            /**
             * Verified Facts
             * @default
             */
            verified_facts: string;
            /**
             * Analysis Judgment
             * @default
             */
            analysis_judgment: string;
            /**
             * Open Questions
             * @default
             */
            open_questions: string;
            /**
             * Recommendation
             * @default
             */
            recommendation: string;
        };
        /** ConclusionUpsertRequest */
        ConclusionUpsertRequest: {
            /** Verified Facts */
            verified_facts: string;
            /** Analysis Judgment */
            analysis_judgment: string;
            /** Open Questions */
            open_questions: string;
            /** Recommendation */
            recommendation: string;
            /** Editor */
            editor: string;
        };
        /** CopilotErrorResponse */
        CopilotErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /** CopilotInteractionResponse */
        CopilotInteractionResponse: {
            /** Interaction Id */
            interaction_id: string;
            /** Outcome */
            outcome: string;
            /** Context Digest */
            context_digest: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Template Version */
            template_version: string;
            answer: components["schemas"]["StructuredAnswer"];
        };
        /** CopilotSection */
        CopilotSection: {
            /** Text */
            text: string;
            /**
             * Citations
             * @default []
             */
            citations: string[];
        };
        /** DashboardContext */
        DashboardContext: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /**
             * Import Version Id
             * Format: uuid
             */
            import_version_id: string;
            /**
             * Metric Snapshot Id
             * Format: uuid
             */
            metric_snapshot_id: string;
            /**
             * Analysis Run Id
             * Format: uuid
             */
            analysis_run_id: string;
            /** As Of Month */
            as_of_month: string;
            /** Metric Definition Set Id */
            metric_definition_set_id: string;
            /** Metric Definition Set Hash */
            metric_definition_set_hash: string;
            /** Metric Engine Version */
            metric_engine_version: string;
            /** Analysis Policy Id */
            analysis_policy_id: string;
            /** Analysis Policy Hash */
            analysis_policy_hash: string;
            /** Analysis Engine Version */
            analysis_engine_version: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** DashboardDegradation */
        DashboardDegradation: {
            /**
             * Panel
             * @enum {string}
             */
            panel: "metric_cards" | "trends" | "profit_bridge" | "findings" | "product_table" | "margin_matrix";
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** DashboardErrorResponse */
        DashboardErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /**
         * DashboardOverviewResponse
         * @description Public read-only Finance BP dashboard response.
         */
        DashboardOverviewResponse: {
            /**
             * State
             * @enum {string}
             */
            state: "ready" | "empty" | "error" | "degraded" | "stale";
            context: components["schemas"]["DashboardContext"];
            filter_options: components["schemas"]["FilterOptions"];
            active_filters: components["schemas"]["ActiveFilters"];
            data_status: components["schemas"]["DataStatus"];
            /** Metric Cards */
            metric_cards: components["schemas"]["MetricCard"][];
            trends: components["schemas"]["TrendPanel"];
            profit_bridge: components["schemas"]["ProfitBridge"];
            /** Findings */
            findings: components["schemas"]["FindingItem"][];
            product_table: components["schemas"]["ProductPerformance"];
            margin_matrix: components["schemas"]["MarginMatrix"];
            /** Highlights */
            highlights: components["schemas"]["Highlight"][];
            /** Degradations */
            degradations: components["schemas"]["DashboardDegradation"][];
        };
        /** DashboardValue */
        DashboardValue: {
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "unavailable" | "degraded";
            /** Exact Value */
            exact_value?: string | null;
            /** Display Value */
            display_value: string;
            /**
             * Semantic Direction
             * @enum {string}
             */
            semantic_direction: "positive" | "negative" | "warning" | "neutral";
            /** Unavailable Code */
            unavailable_code?: string | null;
            /** Unavailable Message */
            unavailable_message?: string | null;
        };
        /** DataStatus */
        DataStatus: {
            /**
             * Batch Status
             * @enum {string}
             */
            batch_status: "draft" | "validating" | "blocked" | "ready" | "published";
            /**
             * Import Status
             * @enum {string}
             */
            import_status: "draft" | "validating" | "blocked" | "ready" | "published";
            /**
             * Quality Status
             * @enum {string}
             */
            quality_status: "passed" | "warning" | "blocked";
            /** Blocking Issue Count */
            blocking_issue_count: number;
            /** Warning Issue Count */
            warning_issue_count: number;
            /** Acknowledged Warning Count */
            acknowledged_warning_count: number;
            /**
             * Reconciliation Status
             * @enum {string}
             */
            reconciliation_status: "passed" | "failed" | "not_available";
            /**
             * Metric Snapshot Status
             * @constant
             */
            metric_snapshot_status: "published";
            /**
             * Analysis Run Status
             * @constant
             */
            analysis_run_status: "published";
            /**
             * Freshness Status
             * @enum {string}
             */
            freshness_status: "fresh" | "stale";
        };
        /** DimensionOption */
        DimensionOption: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** DriverLine */
        DriverLine: {
            /** Position */
            position: number;
            /** Driver Code */
            driver_code: string;
            /** Calculation Method */
            calculation_method: string | null;
            /** Contribution Amount */
            contribution_amount: string;
            /** Contribution Ratio */
            contribution_ratio: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** EvidenceDecisionRequest */
        EvidenceDecisionRequest: {
            /** Decision */
            decision: string;
            /** Reviewer */
            reviewer: string;
            /** Comment */
            comment?: string | null;
        };
        /**
         * EvidenceDecisionResponse
         * @description Acknowledgement of an evidence review decision.
         */
        EvidenceDecisionResponse: {
            /** Finding Id */
            finding_id: string;
            /** Status */
            status: string;
            /** Review Sequence */
            review_sequence: number;
            /** Decision */
            decision: string;
        };
        /** EvidenceLine */
        EvidenceLine: {
            /** Evidence Id */
            evidence_id: string;
            /** Status */
            status: string;
            /** Evidence Type */
            evidence_type: string;
            /** Object Type */
            object_type: string;
            /** Object Id */
            object_id: string;
            /** Note */
            note: string | null;
            /** Evidence Digest */
            evidence_digest: string | null;
        };
        /** FieldMappingResponse */
        FieldMappingResponse: {
            /** Source Header */
            source_header: string;
            /** Source Column */
            source_column: string;
            /** Target Field Id */
            target_field_id: string;
            /** Method */
            method: string;
            /** Score */
            score: number;
            /** Confidence */
            confidence: string;
            /** Requires Confirmation */
            requires_confirmation: boolean;
            /** Rationale */
            rationale: string;
        };
        /** FilterDimension */
        FilterDimension: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "organization" | "customer_segment" | "logistics_product" | "region";
            /** Label */
            label: string;
            /** Options */
            options: components["schemas"]["DimensionOption"][];
        };
        /** FilterOptions */
        FilterOptions: {
            /** Dimensions */
            dimensions: components["schemas"]["FilterDimension"][];
            /** Supported Combinations */
            supported_combinations: ("organization" | "customer_segment" | "logistics_product" | "region")[][];
        };
        /** FindingContext */
        FindingContext: {
            /** Finding Id */
            finding_id: string;
            /** Finding Type */
            finding_type: string | null;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Impact Amount */
            impact_amount: string;
            /** Unit */
            unit: string;
            /** Confidence */
            confidence: string;
            /** Business Meaning */
            business_meaning: string | null;
            /** Fact Statement */
            fact_statement: string | null;
            /** Comparison Basis */
            comparison_basis: string | null;
            /** Total Score */
            total_score: string | null;
            /** Policy Version */
            policy_version: string | null;
            /** Created At */
            created_at: string;
        };
        /** FindingItem */
        FindingItem: {
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Finding Type */
            finding_type: string;
            /** Title */
            title: string;
            impact: components["schemas"]["DashboardValue"];
            /** Total Score */
            total_score: string;
            /**
             * Comparison Basis
             * @enum {string}
             */
            comparison_basis: "prior_year" | "budget";
            /** Evidence Verified */
            evidence_verified: number;
            /** Evidence Total */
            evidence_total: number;
            /**
             * Scope
             * @constant
             */
            scope: "global";
            /** Investigation Path */
            investigation_path: string;
        };
        /** FindingTransitionRequest */
        FindingTransitionRequest: {
            /** Decision */
            decision: string;
            /** Reviewer */
            reviewer: string;
            /** Comment */
            comment?: string | null;
        };
        /**
         * FindingTransitionResponse
         * @description Acknowledgement of a governed Finding state transition.
         */
        FindingTransitionResponse: {
            /** Finding Id */
            finding_id: string;
            /** Status */
            status: string;
            /** Review Sequence */
            review_sequence: number;
            /** Decision */
            decision: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Highlight */
        Highlight: {
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Title */
            title: string;
            /** Impact Display */
            impact_display: string;
        };
        /** ImportVersionResponse */
        ImportVersionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Mapping Version Id */
            mapping_version_id: string | null;
            /** Sequence */
            sequence: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "validating" | "blocked" | "ready" | "published";
            /** Is Published */
            is_published: boolean;
            /** Source File Id */
            source_file_id: string | null;
            /** Issues */
            issues: components["schemas"]["QualityIssueResponse"][];
            /** Reconciliations */
            reconciliations: components["schemas"]["ReconciliationResponse"][];
            /** Next Allowed Actions */
            next_allowed_actions: string[];
        };
        /**
         * InvestigationContextResponse
         * @description Read-only evidence-first Investigation context.
         */
        InvestigationContextResponse: {
            identity: components["schemas"]["InvestigationIdentity"];
            finding: components["schemas"]["FindingContext"];
            result: components["schemas"]["AnalysisResultContext"] | null;
            metric: components["schemas"]["MetricContext"];
            /** Drivers */
            drivers: components["schemas"]["DriverLine"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceLine"][];
            /** Reviews */
            reviews: components["schemas"]["ReviewLine"][];
            /** Quality Issues */
            quality_issues: components["schemas"]["QualityIssueLine"][];
            /** Reconciliations */
            reconciliations: components["schemas"]["ReconciliationLine"][];
            conclusion: components["schemas"]["ConclusionState"];
            /** Source Records */
            source_records: components["schemas"]["SourceRecordLine"][];
            /** Eligibility Blockers */
            eligibility_blockers: string[];
        };
        /** InvestigationErrorResponse */
        InvestigationErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /** InvestigationIdentity */
        InvestigationIdentity: {
            /** Finding Id */
            finding_id: string;
            /** Batch Id */
            batch_id: string;
            /** Metric Snapshot Id */
            metric_snapshot_id: string;
            /** Analysis Run Id */
            analysis_run_id: string;
        };
        /** InvestigationQuestionRequest */
        InvestigationQuestionRequest: {
            /** Question */
            question: string;
            /** Actor */
            actor: string;
            /** Batch Id */
            batch_id?: string | null;
            /** Metric Snapshot Id */
            metric_snapshot_id?: string | null;
            /** Analysis Run Id */
            analysis_run_id?: string | null;
        };
        /** MappingConfirmationRequest */
        MappingConfirmationRequest: {
            /** Actor */
            actor: string;
        };
        /** MappingExplanationRequest */
        MappingExplanationRequest: {
            /** Import Version Id */
            import_version_id: string;
            /** Actor */
            actor: string;
        };
        /** MappingResponse */
        MappingResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Sequence */
            sequence: number;
            /** Mapping Hash */
            mapping_hash: string;
            /** Contract Version */
            contract_version: string;
            /** Sheets */
            sheets: components["schemas"]["SheetMappingResponse"][];
            /** Unresolved Sheet Ids */
            unresolved_sheet_ids: string[];
            /** Ignored Source Sheets */
            ignored_source_sheets: string[];
            /** Confidence Summary */
            confidence_summary: {
                [key: string]: number;
            };
            /** Confirmed By */
            confirmed_by?: string | null;
        };
        /** MarginMatrix */
        MarginMatrix: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "degraded";
            /**
             * Comparison Label
             * @enum {string}
             */
            comparison_label: "预算" | "同比" | "不可用";
            /** Rows */
            rows: components["schemas"]["DimensionOption"][];
            /** Columns */
            columns: components["schemas"]["DimensionOption"][];
            /** Cells */
            cells: components["schemas"]["MatrixCell"][];
            /** Degradation Message */
            degradation_message?: string | null;
        };
        /** MatrixCell */
        MatrixCell: {
            /**
             * Customer Segment Id
             * Format: uuid
             */
            customer_segment_id: string;
            /**
             * Logistics Product Id
             * Format: uuid
             */
            logistics_product_id: string;
            actual_margin: components["schemas"]["DashboardValue"];
            comparison: components["schemas"]["DashboardValue"];
        };
        /** MetricCard */
        MetricCard: {
            /**
             * Metric Code
             * @enum {string}
             */
            metric_code: "orders" | "revenue" | "revenue_per_order" | "gross_margin" | "fulfillment_cost_rate" | "operating_profit" | "ar_balance" | "operating_cash_flow";
            /** Title */
            title: string;
            /** Category */
            category: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "order" | "CNY" | "CNY/order" | "ratio" | "day";
            primary: components["schemas"]["DashboardValue"];
            budget: components["schemas"]["DashboardValue"];
            yoy: components["schemas"]["DashboardValue"];
            ytd_budget: components["schemas"]["DashboardValue"];
            companion: components["schemas"]["DashboardValue"] | null;
        };
        /** MetricContext */
        MetricContext: {
            /** Metric Code */
            metric_code: string | null;
            /** Metric Name */
            metric_name: string | null;
            /** Business Definition */
            business_definition: string | null;
            /** Formula */
            formula: string | null;
            /** Unit */
            unit: string | null;
            /** Definition Version */
            definition_version: number | null;
            /** Engine Version */
            engine_version: string;
            /** Policy Id */
            policy_id: string;
            /** Policy Set Hash */
            policy_set_hash: string;
        };
        /** ProductPerformance */
        ProductPerformance: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "degraded";
            /**
             * Comparison Label
             * @enum {string}
             */
            comparison_label: "预算" | "同比" | "不可用";
            /** Rows */
            rows: components["schemas"]["ProductRow"][];
            /** Degradation Message */
            degradation_message?: string | null;
        };
        /** ProductRow */
        ProductRow: {
            /**
             * Logistics Product Id
             * Format: uuid
             */
            logistics_product_id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            revenue: components["schemas"]["DashboardValue"];
            orders: components["schemas"]["DashboardValue"];
            gross_margin: components["schemas"]["DashboardValue"];
            fulfillment_cost_rate: components["schemas"]["DashboardValue"];
            revenue_comparison: components["schemas"]["DashboardValue"];
            orders_comparison: components["schemas"]["DashboardValue"];
            gross_margin_comparison: components["schemas"]["DashboardValue"];
        };
        /** ProfitBridge */
        ProfitBridge: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "degraded" | "not_applicable";
            /**
             * Comparison Basis
             * @enum {string}
             */
            comparison_basis: "prior_year" | "budget";
            impact: components["schemas"]["DashboardValue"];
            /**
             * Reconciliation Status
             * @enum {string}
             */
            reconciliation_status: "passed" | "failed" | "not_applicable";
            /** Reconciliation Difference */
            reconciliation_difference: string;
            /** Drivers */
            drivers: components["schemas"]["BridgeDriver"][];
            /** Degradation Message */
            degradation_message?: string | null;
        };
        /** QualityIssueLine */
        QualityIssueLine: {
            /** Severity */
            severity: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Acknowledged */
            acknowledged: boolean;
        };
        /** QualityIssueResponse */
        QualityIssueResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocking" | "warning";
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Evidence */
            evidence: string;
            /** Repair Suggestion */
            repair_suggestion: string;
            /** Sheet Name */
            sheet_name: string | null;
            /** Source Row */
            source_row: number | null;
            /** Source Column */
            source_column: string | null;
            /** Acknowledged */
            acknowledged: boolean;
        };
        /** ReconciliationLine */
        ReconciliationLine: {
            /** Reconciliation Code */
            reconciliation_code: string;
            /** Passed */
            passed: boolean;
            /** Expected Value */
            expected_value: string | null;
            /** Actual Value */
            actual_value: string | null;
        };
        /** ReconciliationResponse */
        ReconciliationResponse: {
            /** Code */
            code: string;
            /** Passed */
            passed: boolean;
            /** Expected Value */
            expected_value: string | null;
            /** Actual Value */
            actual_value: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** ReportOutlineRequest */
        ReportOutlineRequest: {
            /** Batch Id */
            batch_id: string;
            /** Actor */
            actor: string;
        };
        /** ReviewLine */
        ReviewLine: {
            /** Sequence */
            sequence: number;
            /** Reviewer */
            reviewer: string;
            /** Decision */
            decision: string;
            /** Comment */
            comment: string | null;
            /** Created At */
            created_at: string;
        };
        /** SheetMappingResponse */
        SheetMappingResponse: {
            /** Source Sheet */
            source_sheet: string;
            /** Target Sheet Id */
            target_sheet_id: string;
            /** Method */
            method: string;
            /** Score */
            score: number;
            /** Fields */
            fields: components["schemas"]["FieldMappingResponse"][];
            /** Unresolved Required Fields */
            unresolved_required_fields: string[];
            /** Ignored Source Headers */
            ignored_source_headers: string[];
        };
        /** SheetProfileResponse */
        SheetProfileResponse: {
            /** Name */
            name: string;
            /** Header Row */
            header_row: number | null;
            /** Data Start Row */
            data_start_row: number | null;
            /** Data End Row */
            data_end_row: number | null;
            /** Data Row Count */
            data_row_count: number;
            /** Columns */
            columns: components["schemas"]["ColumnProfileResponse"][];
        };
        /** SourceRecordLine */
        SourceRecordLine: {
            /** Fact Id */
            fact_id: string;
            /** Month Key */
            month_key: number;
            /** Labels */
            labels: {
                [key: string]: string;
            };
            /** Values */
            values: {
                [key: string]: string;
            };
            /** Source File Name */
            source_file_name: string;
            /** Sheet Name */
            sheet_name: string;
            /** Source Row */
            source_row: number;
            /** Source Column */
            source_column: string;
        };
        /** SourceResponse */
        SourceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** StructuredAnswer */
        StructuredAnswer: {
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["CopilotSection"][];
            /**
             * Judgments
             * @default []
             */
            judgments: components["schemas"]["CopilotSection"][];
            /**
             * Hypotheses
             * @default []
             */
            hypotheses: components["schemas"]["CopilotSection"][];
            /**
             * Questions
             * @default []
             */
            questions: components["schemas"]["CopilotSection"][];
            /**
             * Degradation
             * @default none
             * @enum {string}
             */
            degradation: "none" | "insufficient_data";
        };
        /** TrendPanel */
        TrendPanel: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial_series" | "degraded";
            /** Coverage Count */
            coverage_count: number;
            /**
             * Expected Count
             * @constant
             */
            expected_count: 12;
            /** Missing Months */
            missing_months: string[];
            /** Points */
            points: components["schemas"]["TrendPoint"][];
            /** Degradation Message */
            degradation_message?: string | null;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Month */
            month: string;
            /**
             * Metric Snapshot Id
             * Format: uuid
             */
            metric_snapshot_id: string;
            revenue: components["schemas"]["DashboardValue"];
            operating_profit: components["schemas"]["DashboardValue"];
            gross_margin: components["schemas"]["DashboardValue"];
            operating_cash_flow: components["schemas"]["DashboardValue"];
        };
        /** ValidateImportRequest */
        ValidateImportRequest: {
            /**
             * Mapping Version Id
             * Format: uuid
             */
            mapping_version_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionHistoryResponse */
        VersionHistoryResponse: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Versions */
            versions: components["schemas"]["ImportVersionResponse"][];
        };
        /** WarningAcknowledgementRequest */
        WarningAcknowledgementRequest: {
            /** Actor */
            actor: string;
            /** Reason */
            reason: string;
        };
        /** WarningAcknowledgementResponse */
        WarningAcknowledgementResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Quality Issue Id
             * Format: uuid
             */
            quality_issue_id: string;
            /** Actor */
            actor: string;
            /** Reason */
            reason: string;
        };
        /** WorkbookProfileResponse */
        WorkbookProfileResponse: {
            /**
             * Source File Id
             * Format: uuid
             */
            source_file_id: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sheet Count */
            sheet_count: number;
            /** Sheets */
            sheets: components["schemas"]["SheetProfileResponse"][];
        };
        /** WorkspaceResponse */
        WorkspaceResponse: {
            /**
             * Workspace Id
             * @constant
             */
            workspace_id: "flow-v1";
            /**
             * Name
             * @constant
             */
            name: "FLOW";
            /**
             * Primary Role
             * @constant
             */
            primary_role: "finance_bp";
            /**
             * Industry
             * @constant
             */
            industry: "logistics_supply_chain";
            /** Timezone */
            timezone: string;
            /**
             * Currency
             * @constant
             */
            currency: "CNY";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_workspace_api_v1_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
        };
    };
    create_batch_api_v1_intake_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_api_v1_intake_batches__batch_id__sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_api_v1_intake_batches__batch_id__sources_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_intake_sources__source_file_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbookProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mapping_proposal_api_v1_intake_sources__source_file_id__mapping_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_mapping_api_v1_intake_mappings__mapping_version_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_source_api_v1_intake_sources__source_file_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_warning_api_v1_intake_issues__quality_issue_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quality_issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarningAcknowledgementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarningAcknowledgementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_import_api_v1_intake_imports__import_version_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_history_api_v1_intake_batches__batch_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: {
                period_view?: "month" | "ytd";
                organization_id?: string | null;
                customer_segment_id?: string | null;
                logistics_product_id?: string | null;
                region_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverviewResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardErrorResponse"];
                };
            };
        };
    };
    investigation_context_api_v1_investigations__finding_id__get: {
        parameters: {
            query?: {
                batch_id?: string | null;
                metric_snapshot_id?: string | null;
                analysis_run_id?: string | null;
                source_record_limit?: number;
            };
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationContextResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_evidence_api_v1_investigations__finding_id__evidence__evidence_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceDecisionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_conclusion_api_v1_investigations__finding_id__conclusion_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConclusionUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConclusionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_finding_api_v1_investigations__finding_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingTransitionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_investigation_question_api_v1_copilot_investigations__finding_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotInteractionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotErrorResponse"];
                };
            };
        };
    };
    explain_mapping_api_v1_copilot_explain_mapping_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingExplanationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotInteractionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotErrorResponse"];
                };
            };
        };
    };
    draft_report_outline_api_v1_copilot_report_outline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportOutlineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotInteractionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotErrorResponse"];
                };
            };
        };
    };
}
