"""canonical data

Revision ID: 0002_canonical_data
Revises: 0001_intake_foundation
Create Date: 2026-08-30 09:47:56.042323
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_canonical_data"
down_revision: str | None = "0001_intake_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_customer_segment",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "dim_logistics_product",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("level", sa.String(length=64), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["dim_logistics_product.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "dim_management_account",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("financial_account_code", sa.String(length=128), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["dim_management_account.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "dim_organization",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("level", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["dim_organization.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "dim_period",
        sa.Column("month_key", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("month between 1 and 12", name="ck_dim_period_month"),
        sa.CheckConstraint("month_key = year * 100 + month", name="ck_dim_period_month_key"),
        sa.CheckConstraint("quarter between 1 and 4", name="ck_dim_period_quarter"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("month_key"),
    )
    op.create_table(
        "dim_region",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("province", sa.String(length=128), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["dim_region.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "dim_scenario_version",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("scenario_type", sa.String(length=64), nullable=False),
        sa.Column("version_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "dim_customer",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("tier", sa.String(length=64), nullable=True),
        sa.Column("credit_term_days", sa.Integer(), nullable=True),
        sa.Column("segment_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credit_term_days is null or credit_term_days >= 0",
            name="ck_dim_customer_credit_term_nonnegative",
        ),
        sa.ForeignKeyConstraint(["segment_id"], ["dim_customer_segment.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "fact_ar_collection",
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("invoice_number", sa.String(length=128), nullable=True),
        sa.Column("aging_bucket", sa.String(length=64), nullable=True),
        sa.Column("receivable_balance", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("due_amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("overdue_amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("collected_amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("import_version_id", sa.UUID(), nullable=False),
        sa.Column("source_record_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "invoice_number is not null or aging_bucket is not null",
            name="ck_ar_invoice_or_aging_bucket",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["dim_customer.id"],
        ),
        sa.ForeignKeyConstraint(["import_version_id"], ["import_version.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["dim_period.id"],
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_fact_ar_collection_grain",
        "fact_ar_collection",
        ["period_id", "customer_id", "invoice_number", "aging_bucket"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "fact_budget",
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("customer_segment_id", sa.UUID(), nullable=True),
        sa.Column("logistics_product_id", sa.UUID(), nullable=True),
        sa.Column("management_account_id", sa.UUID(), nullable=True),
        sa.Column("scenario_version_id", sa.UUID(), nullable=False),
        sa.Column("metric_code", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("import_version_id", sa.UUID(), nullable=False),
        sa.Column("source_record_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_segment_id"],
            ["dim_customer_segment.id"],
        ),
        sa.ForeignKeyConstraint(["import_version_id"], ["import_version.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["logistics_product_id"],
            ["dim_logistics_product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["management_account_id"],
            ["dim_management_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["dim_organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["dim_period.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scenario_version_id"],
            ["dim_scenario_version.id"],
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_fact_budget_grain",
        "fact_budget",
        [
            "period_id",
            "organization_id",
            "customer_segment_id",
            "logistics_product_id",
            "management_account_id",
            "scenario_version_id",
            "metric_code",
        ],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "fact_financial_actual",
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("management_account_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("import_version_id", sa.UUID(), nullable=False),
        sa.Column("source_record_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["import_version_id"], ["import_version.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["management_account_id"],
            ["dim_management_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["dim_organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["dim_period.id"],
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "period_id",
            "organization_id",
            "management_account_id",
            name="uq_financial_actual_grain",
        ),
    )
    op.create_table(
        "fact_operating_actual",
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("logistics_product_id", sa.UUID(), nullable=False),
        sa.Column("region_id", sa.UUID(), nullable=False),
        sa.Column("order_count", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("shipment_count", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("warehousing_cost", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("transportation_cost", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("other_direct_cost", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("import_version_id", sa.UUID(), nullable=False),
        sa.Column("source_record_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["dim_customer.id"],
        ),
        sa.ForeignKeyConstraint(["import_version_id"], ["import_version.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["logistics_product_id"],
            ["dim_logistics_product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["dim_organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["dim_period.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["dim_region.id"],
        ),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_record.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "period_id",
            "organization_id",
            "customer_id",
            "logistics_product_id",
            "region_id",
            name="uq_operating_actual_grain",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_operating_actual")
    op.drop_table("fact_financial_actual")
    op.drop_index(
        "uq_fact_budget_grain", table_name="fact_budget", postgresql_nulls_not_distinct=True
    )
    op.drop_table("fact_budget")
    op.drop_index(
        "uq_fact_ar_collection_grain",
        table_name="fact_ar_collection",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_table("fact_ar_collection")
    op.drop_table("dim_customer")
    op.drop_table("dim_scenario_version")
    op.drop_table("dim_region")
    op.drop_table("dim_period")
    op.drop_table("dim_organization")
    op.drop_table("dim_management_account")
    op.drop_table("dim_logistics_product")
    op.drop_table("dim_customer_segment")
    # ### end Alembic commands ###
