"""analytics and publishing

Revision ID: 0003_analytics_and_publishing
Revises: 0002_canonical_data
Create Date: 2026-08-30 09:51:16.302083
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003_analytics_and_publishing"
down_revision: str | None = "0002_canonical_data"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_definition",
        sa.Column("metric_code", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("business_definition", sa.Text(), nullable=False),
        sa.Column("formula", sa.Text(), nullable=False),
        sa.Column("aggregation", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("format_pattern", sa.String(length=64), nullable=True),
        sa.Column("effective_from_month", sa.Integer(), nullable=True),
        sa.Column("target_value", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("warning_threshold", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("critical_threshold", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column(
            "definition_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name="ck_metric_definition_version_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("metric_code", "version", name="uq_metric_definition_code_version"),
    )
    op.create_table(
        "metric_snapshot",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("engine_version", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name="ck_metric_snapshot_version_positive"),
        sa.ForeignKeyConstraint(["batch_id"], ["analysis_batch.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "version", name="uq_metric_snapshot_batch_version"),
    )
    op.create_table(
        "finding",
        sa.Column("metric_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("impact_amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("business_meaning", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('candidate', 'in_review', 'approved', 'rejected')", name="ck_finding_status"
        ),
        sa.CheckConstraint("confidence between 0 and 1", name="ck_finding_confidence_range"),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"], ["metric_definition.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["metric_snapshot_id"], ["metric_snapshot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metric_value",
        sa.Column("metric_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=False),
        sa.Column("comparison_type", sa.String(length=32), nullable=False),
        sa.Column("period_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("customer_segment_id", sa.UUID(), nullable=True),
        sa.Column("logistics_product_id", sa.UUID(), nullable=True),
        sa.Column("region_id", sa.UUID(), nullable=True),
        sa.Column("value", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["dim_customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_segment_id"],
            ["dim_customer_segment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["logistics_product_id"],
            ["dim_logistics_product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"], ["metric_definition.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["metric_snapshot_id"], ["metric_snapshot.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["dim_organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["dim_period.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["dim_region.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_metric_value_snapshot_grain",
        "metric_value",
        [
            "metric_snapshot_id",
            "metric_definition_id",
            "comparison_type",
            "period_id",
            "organization_id",
            "customer_id",
            "customer_segment_id",
            "logistics_product_id",
            "region_id",
        ],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "report_snapshot",
        sa.Column("metric_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("template_code", sa.String(length=128), nullable=False),
        sa.Column(
            "presentation_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name="ck_report_snapshot_version_positive"),
        sa.ForeignKeyConstraint(
            ["metric_snapshot_id"], ["metric_snapshot.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "metric_snapshot_id", "version", name="uq_report_snapshot_metric_version"
        ),
    )
    op.create_table(
        "conclusion",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("verified_facts", sa.Text(), nullable=False),
        sa.Column("analysis_judgment", sa.Text(), nullable=False),
        sa.Column("open_questions", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["finding_id"], ["finding.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("finding_id"),
    )
    op.create_table(
        "driver_contribution",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("driver_code", sa.String(length=128), nullable=False),
        sa.Column("calculation_method", sa.Text(), nullable=True),
        sa.Column("contribution_amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("contribution_ratio", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position > 0", name="ck_driver_contribution_position_positive"),
        sa.ForeignKeyConstraint(["finding_id"], ["finding.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("finding_id", "position", name="uq_driver_contribution_order"),
    )
    op.create_table(
        "evidence",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("object_id", sa.String(length=128), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "object_type in ('metric', 'finding', 'evidence', 'source_record')",
            name="ck_evidence_object_type",
        ),
        sa.CheckConstraint(
            "status in ('pending', 'verified', 'rejected')", name="ck_evidence_status"
        ),
        sa.ForeignKeyConstraint(["finding_id"], ["finding.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publication_attempt",
        sa.Column("report_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stored_object_id", sa.UUID(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format in ('pptx', 'xlsx', 'html', 'pdf')", name="ck_publication_attempt_format"
        ),
        sa.CheckConstraint(
            "status in ('queued', 'running', 'succeeded', 'failed')",
            name="ck_publication_attempt_status",
        ),
        sa.CheckConstraint("sequence > 0", name="ck_publication_attempt_sequence_positive"),
        sa.ForeignKeyConstraint(["report_snapshot_id"], ["report_snapshot.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stored_object_id"], ["stored_object.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "report_snapshot_id", "sequence", name="uq_publication_attempt_report_sequence"
        ),
    )
    op.create_table(
        "report_snapshot_item",
        sa.Column("report_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("object_id", sa.String(length=128), nullable=False),
        sa.Column(
            "presentation_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "object_type in ('metric', 'finding', 'evidence', 'conclusion')",
            name="ck_report_snapshot_item_object_type",
        ),
        sa.CheckConstraint("position > 0", name="ck_report_snapshot_item_position_positive"),
        sa.ForeignKeyConstraint(["report_snapshot_id"], ["report_snapshot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_snapshot_id", "position", name="uq_report_snapshot_item_order"),
    )
    op.create_table(
        "review_event",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("reviewer", sa.String(length=255), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision in ('submitted', 'approved', 'rejected', 'returned')",
            name="ck_review_event_decision",
        ),
        sa.CheckConstraint("sequence > 0", name="ck_review_event_sequence_positive"),
        sa.ForeignKeyConstraint(["finding_id"], ["finding.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("finding_id", "sequence", name="uq_review_event_finding_sequence"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_event")
    op.drop_table("report_snapshot_item")
    op.drop_table("publication_attempt")
    op.drop_table("evidence")
    op.drop_table("driver_contribution")
    op.drop_table("conclusion")
    op.drop_table("report_snapshot")
    op.drop_index(
        "uq_metric_value_snapshot_grain",
        table_name="metric_value",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_table("metric_value")
    op.drop_table("finding")
    op.drop_table("metric_snapshot")
    op.drop_table("metric_definition")
    # ### end Alembic commands ###
